# Generated by Django 5.2.1 on 2025-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcreatorpost',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
