# Generated by Django 5.2.1 on 2025-06-16 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_creator', '0003_alter_blogcreatorpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blogcreatorpost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_creator.blogcreatorpost'),
            preserve_default=False,
        ),
    ]
