# Generated by Django 5.2.1 on 2025-06-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_creator', '0004_comment_blogcreatorpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcreatorpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_creator.category'),
        ),
    ]
