# Generated by Django 5.2.1 on 2025-06-18 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_creator', '0005_alter_blogcreatorpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcreatorpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog_creator.category'),
        ),
    ]
